In [1]:
import torch

In [21]:
pr = torch.randint(0, 3, (1, 512))
p = torch.randn(1, 512, 768)
print(pr.shape, p.shape)

torch.Size([1, 512]) torch.Size([1, 512, 768])


In [22]:
pr

tensor([[0, 2, 1, 1, 1, 0, 1, 2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 2, 0, 0, 1, 1, 1, 2,
         0, 1, 1, 1, 2, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2,
         1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 1, 2, 1, 0, 0,
         0, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2, 1, 2,
         1, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2,
         0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2,
         0, 2, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 0, 1, 2, 2,
         0, 0, 0, 2, 2, 2, 1, 1, 0, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1,
         2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 2, 0, 2, 1, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1,
         1, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 2, 0, 0, 2, 0,
         1, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 1, 0,
         0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0,
         0, 1, 2, 2, 0, 0, 1

In [33]:
def embedding_matching_turn(role_ids, embeddings):
    # 역할: turn 단위의 임베딩 -> turn과 embedding 매칭 후 풀링(평균)
    
    embeddings_turn = []
    start_idx = 0
    role_ids_cpu = role_ids.cpu().numpy()[0]

    for i in range(1, len(role_ids_cpu)):
        if role_ids_cpu[i] != role_ids_cpu[i-1]:
            turn = embeddings[:, start_idx:i, :].mean(dim=1)
            print(turn)
            embeddings_turn.append(turn)
            start_idx = i

    turn = embeddings[:, start_idx:, :].mean(dim=1)
    print(turn)
    embeddings_turn.append(turn)

    embeddings_turn = torch.cat(embeddings_turn, dim=0)
    return embeddings_turn

In [23]:
# print("pr:", pr[i].shape) # torch.Size([1, 512])
# print("p:", p[i].shape) # torch.Size([1, 512, 768])

# pr = pr[i]를 의미, p = p[i]를 의미
pr


tensor([[0, 2, 1, 1, 1, 0, 1, 2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 2, 0, 0, 1, 1, 1, 2,
         0, 1, 1, 1, 2, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2,
         1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 1, 2, 1, 0, 0,
         0, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2, 1, 2,
         1, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2,
         0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2,
         0, 2, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 0, 1, 2, 2,
         0, 0, 0, 2, 2, 2, 1, 1, 0, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1,
         2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 2, 0, 2, 1, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1,
         1, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 2, 0, 0, 2, 0,
         1, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 1, 0,
         0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0,
         0, 1, 2, 2, 0, 0, 1

In [29]:
def embedding_matching_turn(pr, p): # role_ids, embeddings
    '''
    role_ids를 이용해 embedding 결과를 turn 단위로 묶어서 결과를 리스트로 반환하는 함수
    우선 대화자를 speaker라고 변수 이름 붙였는데, 상의 필요
    '''
    turn_emb_ls = []

    # pr을 1차원 리스트로 변환
    pr_ls = pr.squeeze().tolist()

    # 현재 발화자와 그 발화자의 연속 횟수를 파악하기 위한 변수
    current_speaker = pr_ls[0]
    count = 1

    for i in range(1, len(pr_ls)):
        if pr_ls[i] == current_speaker:
            count += 1
        else:
            # 이전 발화자의 임베딩 결과를 새로운 리스트에 저장
            turn_emb_ls.append(p[:, i-count:i, :].squeeze(0))
            # 새로운 발화자와 카운트 업데이트
            current_speaker = pr_ls[i]
            count = 1

    # 마지막 발화자 처리
    turn_emb_ls.append(p[:, len(pr_ls)-count:len(pr_ls), :].squeeze(0))
    
    return turn_emb_ls

In [54]:
turn_emb_ls = embedding_matching_turn(pr, p)
len(turn_emb_ls)

335

In [151]:
turn_emb_ls[0].shape

torch.Size([1, 768])

In [31]:
pr

tensor([[0, 2, 1, 1, 1, 0, 1, 2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 2, 0, 0, 1, 1, 1, 2,
         0, 1, 1, 1, 2, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2,
         1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 0, 0, 2, 1, 2, 1, 0, 0,
         0, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 0, 2, 0, 1, 1, 2, 2, 1, 2,
         1, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 0, 2, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2,
         0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 2, 2,
         0, 2, 1, 0, 2, 0, 2, 1, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 1, 1, 0, 1, 2, 2,
         0, 0, 0, 2, 2, 2, 1, 1, 0, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1,
         2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 2, 0, 2, 1, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1,
         1, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 2, 0, 0, 2, 0,
         1, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 0, 1, 0,
         0, 0, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0,
         0, 1, 2, 2, 0, 0, 1

In [56]:
from itertools import groupby

def find_most_frequent_speaker(pr): # role_ids
    '''
    가장 많이 등장한 대화자 찾고, turn 단위로 idx 새로 생성하는 함수
    '''
    pr_ls = pr.squeeze().tolist()
    speaker_counts = {}
    turn_idx_ls = []

    # 각 대화자의 등장 횟수 카운트
    for speaker, _ in groupby(pr_ls):
        turn_idx_ls.append(speaker)
        if speaker in speaker_counts:
            speaker_counts[speaker] += 1
        else:
            speaker_counts[speaker] = 1
            
    most_frequent_speaker = max(speaker_counts, key=speaker_counts.get)
    most_frequent_count = speaker_counts[most_frequent_speaker]

    # print(f"가장 많이 등장한 대화자: 대화자 {most_frequent_speaker}, 등장 횟수: {most_frequent_count}")
    return turn_idx_ls, most_frequent_speaker


In [50]:
# print(speaker_counts[0]) # 109
# print(speaker_counts[2]) # 110
turn_emb_ls = embedding_matching_turn(pr, p)
turn_idx_ls, most_frequent_speaker = find_most_frequent_speaker(pr)


In [58]:
print(most_frequent_speaker)
print(len(turn_emb_ls))
print(len(turn_idx_ls))

1
335
335


In [156]:
import random

def set_anchor(turn_idx_ls, turn_emb_ls, most_frequent_speaker, window=2):
    '''
    # anchor를 정하는 함수
    '''
    # 기준이 되는 대화자(=most_frequent_speaker)의 인덱스 중 1개 랜덤 샘플링
    speaker_turns = [i for i, speaker in enumerate(turn_idx_ls) if speaker == most_frequent_speaker]
    print("speaker_turns:", speaker_turns)
    
    # window 사이즈만큼 앞뒤 인덱스를 제외한 범위에서 랜덤하게 하나의 인덱스를 선택
    valid_indices = [idx for idx in speaker_turns if window <= idx < len(turn_idx_ls) - window]
    print("valid_indices:", valid_indices)
    anchor_turn_idx = random.choice(valid_indices)
    
    # window 사이즈를 고려하여 anchor에 포함될 turn의 인덱스 범위를 계산
    start_idx = anchor_turn_idx - window
    end_idx = anchor_turn_idx + window
    print("start_idx:", start_idx)
    print("end_idx:", end_idx)
    # start_idx = max(0, anchor_turn_idx - window)
    # end_idx = min(len(turn_emb_ls), anchor_turn_idx + window + 1)
    
    # 계산된 범위에 해당하는 turn_emb_ls의 값을 가져와서 앵커로 설정
    anchor = turn_emb_ls[start_idx:end_idx+1]
    
    # anchor 리스트의 각 요소를 [1, 768]이 되도록 mean pooling
    pooled_anchor = [tensor.mean(dim=0, keepdim=True) for tensor in anchor]
    # mean pooling 결과를 stack: [len(anchor), 768]
    pooled_anchor = torch.stack(pooled_anchor, dim=0).squeeze()
    
    return valid_indices, anchor_turn_idx, anchor, pooled_anchor

In [147]:
def generate_pairs(valid_indices, anchor_turn_idx, anchor, turn_emb_ls, window=2):
    '''
    pair, hard pair를 생성하는 함수
    pos를 기준으로 변수를 정의한 것으로, pair의 경우 anchor에 stride를 적용하고, hard pair는 anchor_turn_idx에서 가장 거리가 먼 turn(동일 대화자)을 이용
    '''
    
    # stride 정의: anchor 길이 // 2
    stride = len(anchor) // 2
    print(stride)
    
    # Pair
    pair_start_idx = (anchor_turn_idx + window) - stride + 1 # anchor_turn_idx + window: anchor의 end_idx
    pair_end_idx = pair_start_idx + len(anchor) - 1
    pair = turn_emb_ls[pair_start_idx:pair_end_idx+1]
    print(pair_start_idx)
    print(pair_end_idx)
    
    # Hard Pair: anchor_turn_idx에서 가장 거리가 먼 turn (동일 대화자)
    dist_to_first = abs(anchor_turn_idx - valid_indices[0])
    dist_to_last = abs(anchor_turn_idx - valid_indices[-1])
    
    # 더 큰 거리를 가진 인덱스 선택
    if dist_to_first > dist_to_last:
        farther_index = valid_indices[0]
    else:
        farther_index = valid_indices[-1]
    
    hard_start_idx = farther_index - window
    hard_end_idx = farther_index + window
    hard_pair = turn_emb_ls[hard_start_idx:hard_end_idx+1]
    
    # pair, hard_pair 리스트의 각 요소를 [1, 768]이 되도록 mean pooling
    pooled_pair = [tensor.mean(dim=0, keepdim=True) for tensor in pair]
    pooled_hard_pair = [tensor.mean(dim=0, keepdim=True) for tensor in hard_pair]
    
    # mean pooling 결과를 stack: [len(pooled_pair), 768], [len(pooled_hard_pair), 768]
    pooled_pair = torch.stack(pooled_pair, dim=0).squeeze()
    pooled_hard_pair = torch.stack(pooled_hard_pair, dim=0).squeeze()
    
    return pair, hard_pair, pooled_pair, pooled_hard_pair

In [157]:
valid_indices, anchor_turn_idx, anchor, pooled_anchor = set_anchor(turn_idx_ls, turn_emb_ls, most_frequent_speaker)
print()
print(anchor_turn_idx)
print(len(anchor))
print(anchor[0].shape)
print(anchor[1].shape)
print(anchor[2].shape)
print(anchor[3].shape)
print(anchor[4].shape)
print()
print(pooled_anchor[0].shape)
print(pooled_anchor[1].shape)
print(pooled_anchor[2].shape)
print(pooled_anchor[3].shape)
print(pooled_anchor[4].shape)

speaker_turns: [2, 4, 8, 12, 15, 17, 22, 25, 27, 30, 32, 36, 39, 43, 45, 48, 50, 52, 59, 61, 63, 67, 69, 72, 74, 77, 80, 84, 86, 89, 92, 97, 102, 106, 109, 111, 115, 118, 120, 122, 124, 126, 128, 130, 134, 137, 140, 142, 145, 147, 149, 151, 154, 159, 162, 164, 166, 169, 171, 174, 176, 179, 181, 186, 189, 191, 197, 202, 205, 207, 210, 212, 214, 218, 220, 223, 227, 229, 231, 233, 235, 237, 243, 245, 247, 249, 254, 256, 258, 261, 263, 267, 272, 274, 276, 278, 281, 283, 285, 290, 292, 296, 298, 300, 302, 304, 306, 310, 313, 315, 319, 324, 326, 328, 330, 334]
valid_indices: [2, 4, 8, 12, 15, 17, 22, 25, 27, 30, 32, 36, 39, 43, 45, 48, 50, 52, 59, 61, 63, 67, 69, 72, 74, 77, 80, 84, 86, 89, 92, 97, 102, 106, 109, 111, 115, 118, 120, 122, 124, 126, 128, 130, 134, 137, 140, 142, 145, 147, 149, 151, 154, 159, 162, 164, 166, 169, 171, 174, 176, 179, 181, 186, 189, 191, 197, 202, 205, 207, 210, 212, 214, 218, 220, 223, 227, 229, 231, 233, 235, 237, 243, 245, 247, 249, 254, 256, 258, 261, 263, 267

In [158]:
print(pooled_anchor.shape)

torch.Size([5, 768])


In [149]:
pair, hard_pair, pooled_pair, pooled_hard_pair = generate_pairs(valid_indices, anchor_turn_idx, anchor, turn_emb_ls)
print(len(pair))
print(len(hard_pair))
print()
print(pair[0].shape)
print(pair[1].shape)
print(pair[2].shape)
print(pair[3].shape)
print(pair[4].shape)
print()
print(hard_pair[0].shape)
print(hard_pair[1].shape)
print(hard_pair[2].shape)
print(hard_pair[3].shape)
print(hard_pair[4].shape)
print()
print(pooled_pair.shape)
print(pooled_hard_pair.shape)

2
163
167
5
5

torch.Size([4, 768])
torch.Size([1, 768])
torch.Size([4, 768])
torch.Size([1, 768])
torch.Size([1, 768])

torch.Size([1, 768])
torch.Size([2, 768])
torch.Size([1, 768])
torch.Size([1, 768])
torch.Size([1, 768])

torch.Size([5, 768])
torch.Size([5, 768])


In [145]:
hard_pair

[tensor([[ 1.2360e+00, -2.2005e-01,  1.2832e+00,  6.2841e-01,  1.1682e+00,
           6.2191e-01,  1.2951e-01,  1.5507e+00, -4.4029e-01,  1.2335e-01,
           8.6682e-01,  1.0188e+00, -1.1494e+00,  7.3866e-01, -5.6938e-01,
          -3.1079e-01, -1.9289e-02, -3.8849e-01,  1.0230e+00,  3.9778e-01,
          -1.2347e+00,  5.4998e-01,  3.4285e-01,  1.7455e-01, -1.0159e+00,
          -9.8397e-01,  8.2854e-01,  5.2293e-01,  2.0802e+00,  8.9504e-01,
           8.2460e-01, -4.7735e-01,  9.3143e-01,  3.2714e-01,  1.3411e+00,
          -3.6870e-01,  1.5542e-01,  2.6178e-01, -5.5509e-01,  2.3594e+00,
          -9.1867e-01,  3.0590e-01, -7.1807e-01, -2.9100e-01,  2.6269e+00,
           2.4692e+00, -1.1913e+00,  1.0985e+00,  8.8238e-01,  7.2075e-01,
           9.5437e-01,  1.0565e+00,  2.6728e-01,  8.5997e-01,  1.5632e+00,
          -6.9354e-01, -2.7360e-01, -4.0745e-01, -1.3306e-02, -5.7399e-01,
           6.6548e-01,  2.5754e-01,  1.1849e-01, -1.1243e+00, -7.5320e-01,
          -1.0047e+00, -8